# Generated by Django 3.2.4 on 2023-03-27 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjeddits', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=40000)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created')),
                ('subjeddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjeddits.subjeddit')),
            ],
        ),
    ]
