# Generated by Django 3.2.4 on 2023-03-16 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjeddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=21)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subjeddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjeddits.subjeddit')),
            ],
        ),
    ]
