# Generated by Django 3.2.4 on 2023-03-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjeddits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
