# Generated by Django 3.2.4 on 2023-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjeddits', '0003_subjeddit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjeddit',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
